- name: update apt
  apt:
    update_cache: yes
  changed_when: false

- name: Install packages 
  apt:
    pkg: 
      - sudo
      - vlan
      - dnsmasq
      - ddclient
      - iptables
      - iptables-persistent
      - tcpdump
      - net-tools
      - python3-pexpect #pre-requisite for restarting iptables with expect
      - curl
      - nmap
      - dnsutils
      - snmp
      - snmpd
    
- name: add user to sudoers
  lineinfile:
    path: /etc/sudoers
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
    insertafter: "%sudo ALL=(ALL:ALL) ALL"
    state: present

- name: Add community to snmpd
  lineinfile:
    dest: /etc/snmp/snmpd.conf
    line: "rocommunity {{ password }}"
    insertafter: "rocommunity  public default -V systemonly"
    state: present
  register: snmpd_update

- name: Remove v4 SNMP string from snmpd.conf
  lineinfile:
    path: /etc/snmp/snmpd.conf
    line: 'rocommunity public default -V systemonly'
    state: absent
  register: snmpd_update2

- name: Replace agentaddress with publically accessible
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^agentaddress'
    line: 'agentaddress udp:161'
    state: present
  register: snmpd_update3

- name: remove v6 SNMP string from snmpd.conf
  lineinfile:
    path: /etc/snmp/snmpd.conf
    line: 'rocommunity6 public default -V systemonly'
    state: absent
  register: snmpd_update4

